# Generated by Django 4.2.7 on 2026-06-05 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-borrow_count', '-created_at'], 'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'ordering': ['-borrow_date'], 'verbose_name': '借阅记录', 'verbose_name_plural': '借阅记录'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='book',
            name='borrow_count',
            field=models.IntegerField(default=0, verbose_name='借阅次数'),
        ),
        migrations.AddField(
            model_name='book',
            name='reservation_count',
            field=models.IntegerField(default=0, verbose_name='预约次数'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='罚款缴纳时间'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='max_renew_count',
            field=models.IntegerField(default=2, verbose_name='最大续借次数'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='renew_count',
            field=models.IntegerField(default=0, verbose_name='续借次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('reader', '读者')], default='reader', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_position', models.IntegerField(default=1, verbose_name='排队位置')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('available', '可借阅'), ('completed', '已完成'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预约日期')),
                ('available_notify_date', models.DateTimeField(blank=True, null=True, verbose_name='可借通知日期')),
                ('expire_date', models.DateTimeField(verbose_name='过期日期')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.book', verbose_name='图书')),
                ('borrow_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='api.borrowrecord', verbose_name='关联借阅记录')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='读者')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'ordering': ['-reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='RenewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请日期')),
                ('renew_days', models.IntegerField(default=30, verbose_name='续借天数')),
                ('original_due_date', models.DateTimeField(verbose_name='原应还日期')),
                ('new_due_date', models.DateTimeField(blank=True, null=True, verbose_name='新应还日期')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='审核日期')),
                ('review_remark', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renew_records', to='api.book', verbose_name='图书')),
                ('borrow_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renew_records', to='api.borrowrecord', verbose_name='借阅记录')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renew_records', to=settings.AUTH_USER_MODEL, verbose_name='读者')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_renews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '续借记录',
                'verbose_name_plural': '续借记录',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('borrow', '借书'), ('return', '还书'), ('renew', '续借'), ('reserve', '预约'), ('fine', '罚款'), ('login', '登录'), ('logout', '退出'), ('import', '导入'), ('export', '导出'), ('other', '其他')], max_length=50, verbose_name='操作类型')),
                ('target_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标模型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('target_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='目标名称')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(default='overdue', max_length=50, verbose_name='罚款类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='罚款金额')),
                ('days_overdue', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('status', models.CharField(choices=[('unpaid', '未缴纳'), ('paid', '已缴纳'), ('waived', '已减免')], default='unpaid', max_length=20, verbose_name='状态')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '现金'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('card', '刷卡'), ('transfer', '转账')], max_length=20, null=True, verbose_name='支付方式')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='缴纳日期')),
                ('waiver_reason', models.TextField(blank=True, null=True, verbose_name='减免原因')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_records', to='api.book', verbose_name='图书')),
                ('borrow_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_records', to='api.borrowrecord', verbose_name='借阅记录')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_fines', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_records', to=settings.AUTH_USER_MODEL, verbose_name='读者')),
            ],
            options={
                'verbose_name': '罚金记录',
                'verbose_name_plural': '罚金记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
